events {}

http {
    server {
        listen 80;
	
	client_max_body_size 200M;

	error_page 413 /413.html;

	location = /413.html {
	    root /usr/share/nginx/html;
	}

        location / {
            proxy_pass http://web:5000;
        }
    }
}
